lr: 0.001
num_hidden: 1024
num_heads: 8
num_out_heads: 1
num_layers: 1
self_loop: False
weight_decay: 2e-4
max_epoch: 900
mask_rate: 0.3
encoder: gat
decoder: gat
activation: prelu
attn_drop: 0.1
in_drop: 0.1
loss_fn: sce
drop_edge_rate: 0.0
optimizer: adam
replace_rate: 0.05
alpha_l: 3
scheduler: True
remask_method: random
momentum: 0
lam: 0.2
bet: 0.02
# lam: 0
# bet: 0